//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Northwind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int userId { get; set; }
        
        [Required(ErrorMessage = "Kullan?c? ad? bos gecilemez")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "?ifre bo? gecilemez")]
        public string Password { get; set; }
    }
}
